{
  "openapi": "3.0.1",
  "info": {
    "title": "Agroex API",
    "description": "Spring Boot Application",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ]
}