spring:
  datasource:
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/agroex_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration