spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
#  supported-extensions-path:
currency-api:
  key: ${CURRENCY_API_KEY}
  url: ${CURRENCY_URL}