global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/sys/metrics'
    scrape_interval: 30s
    static_configs:
      - targets:
          - agroex-api:8080
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'